---
- name: Update and Upgrade Ubuntu Packages
  hosts: ubuntu
  become: true
  tasks:
    - name: Update and upgrade Ubuntu packages
      apt:
        update_cache: yes
        upgrade: dist
      when: ansible_distribution == 'Ubuntu'

- name: Install NTP on Ubuntu
  tags: ntp
  hosts: ubuntu
  become: true
  tasks:
    - name: Install NTP
      apt:
        name: ntp
        state: present
      tags:
        - ntp  

- name: Install OpenStack Packages on Ubuntu
  tags: setup
  hosts: ubuntu
  become: true
  tasks:
    - name: Install OpenStack packages (controller services)
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - python3-openstackclient
        - nova-api
        - nova-scheduler
        - nova-conductor
        - openstack-dashboard
        - rabbitmq-server
        - memcached
        - apache2
        - libapache2-mod-wsgi-py3
        - neutron-server
        - keystone
        - glance
      when: ansible_distribution == 'Ubuntu'
      tags:
        - openstack_packages

- name: Install SQL Database (MySQL) on Ubuntu
  tags: mysql
  hosts: ubuntu
  become: true
  tasks:
    - name: Install MySQL Server Core
      apt:
        name: mysql-server-core-8.0
        state: present
      tags:
        - mysql 

    - name: Install MySQL Server 8.0
      apt:
        name: mysql-server-8.0
        state: present

    - name: Start MySQL Service
      service:
        name: mysql
        state: restarted
        enabled: yes
      tags:
        - mysql_service  

- name: Install Message Queue (RabbitMQ) on Ubuntu
  tags: rabbit
  hosts: ubuntu
  become: true
  tasks:
    - name: Install RabbitMQ
      apt:
        name: rabbitmq-server
        state: present
      tags:
        - rabbitmq 

    - name: Start RabbitMQ Service
      service:
        name: rabbitmq-server
        state: started
        enabled: yes
      tags:
        - rabbitmq_service 

- name: Install Memcached on Ubuntu
  tags: memcached
  hosts: ubuntu
  become: true
  tasks:
    - name: Install Memcached
      apt:
        name: memcached
        state: present
      tags:
        - memcached 

    - name: Start Memcached Service
      service:
        name: memcached
        state: started
        enabled: yes
      tags:
        - memcached_service 

- name: Install and Configure Etcd on Ubuntu
  tags: etcd
  hosts: ubuntu
  become: true
  tasks:
    - name: Download Etcd Binary
      get_url:
        url: "https://github.com/etcd-io/etcd/releases/download/v3.5.9/etcd-v3.5.9-linux-amd64.tar.gz"
        dest: "/tmp/etcd-v3.5.9-linux-amd64.tar.gz"

    - name: Extract Etcd Binary
      unarchive:
        src: "/tmp/etcd-v3.5.9-linux-amd64.tar.gz"
        dest: "/usr/local/bin/"
        remote_src: yes

    - name: Move Etcd and Etcdctl to System Path
      copy:
        src: "/usr/local/bin/etcd-v3.5.9-linux-amd64/etcd"
        dest: "/usr/local/bin/etcd"
        remote_src: yes
        mode: '0755'

    - name: Move Etcdctl to System Path
      copy:
        src: "/usr/local/bin/etcd-v3.5.9-linux-amd64/etcdctl"
        dest: "/usr/local/bin/etcdctl"
        remote_src: yes
        mode: '0755'

    - name: Create Etcd Systemd Service File
      copy:
        content: |
          [Unit]
          Description=etcd
          Documentation=https://github.com/etcd-io/etcd
          After=network.target

          [Service]
          ExecStart=/usr/local/bin/etcd
          Restart=always
          RestartSec=5

          [Install]
          WantedBy=multi-user.target
        dest: /etc/systemd/system/etcd.service
        mode: '0644'

    - name: Reload Systemd Daemon
      command: systemctl daemon-reload

    - name: Enable and Start Etcd Service
      service:
        name: etcd
        state: started
        enabled: yes
      tags:
        - etcd_service

